### PR TITLE
Fix the height issue of the img tags

### LINKED ISSUE #69: Lack of height attributes for images in scaladocs displays poorly in IntelliJ/IDEA
"Dennis ‏@dnvriend: Too bad #IntelliJIDEA 14 flattens the pretty rxjava images when showing the documentation.. oh well" (https://twitter.com/dnvriend/status/539311261637685248)

This seems to be because the images in the scaladocs do not have height attributes. If you add that attribute to the image elements this problem may go away.  You can use the RxJava source as a guide for that, as the (mostly) same set of images are there complete with height attributes.

### PR DESCRIPTION
**Pull request by zsxwing**
Fix #69.

docs

The new img tags are generated by the following codes:

``` Scala
import java.io.File
import java.net.URL
import javax.swing.ImageIcon

import scala.io._
import scala.collection.mutable

object Main {

  def imageMeta(imgURL: String): (Int, Int) = {
    val imageIcon = new ImageIcon(new URL(imgURL))
    (imageIcon.getIconWidth(), imageIcon.getIconHeight())
  }

  def clearImg(file: String): Unit = {

    val img = """<img.*src="(.*?)".*>""".r

    val urlImgCache = mutable.Map[String, String]()

    for (line <- Source.fromFile(new File(file))(Codec.UTF8).getLines()) {
      val newLine = img.findFirstMatchIn(line) map {
        imgTag => {
          val tagContent = imgTag group 0
          val url = imgTag group 1
          val newImgTag = if (urlImgCache.contains(url)) {
            urlImgCache(url)
          } else {
            val (width, height) = imageMeta(url)
            val ratio = 640.0 / width
            val scaleHeight = (height * ratio).toInt
            val newImgTag = s"""<img width="640" height="${scaleHeight}" src="${url}" alt="" />"""
            urlImgCache += url -> newImgTag
            newImgTag
          }
          line.replace(tagContent, newImgTag)
        }
      } getOrElse (line)
      println(newLine)
    }
  }

  def main(args: Array[String]): Unit = {
    clearImg("/home/zsx/workspace/RxScala/src/main/scala/rx/lang/scala/Observable.scala")
  }
}
```

### CODE REVIEW

**Comment by samuelgruetter** [comment]
Did you check if the html generated by scaladoc still looks ok? Just to be sure...

**Comment by zsxwing** [comment]
> Did you check if the html generated by scaladoc still looks ok? Just to be sure...

Yes. I also realized the links are still old although they can redirect to the correct address, such as `https://raw.github.com/wiki/Netflix/RxJava/images/rx-operators/toMap.png`. I'm working on updating them.

**Comment by zsxwing** [comment]
I published the new Scaladoc of this PR here: http://code.iamzsx.me/RxScala/#package

**Comment by samuelgruetter** [comment]
LGTM, thanks :)

**Pull request merged**
