### PR TITLE
Update to Rxjava 1.0.8 & add onBackpressureDropDo to ExperimentalAPIs

### PR DESCRIPTION
**Pull request by zsxwing**

### CODE REVIEW

**Comment by samuelgruetter** [comment]
In RxJava, both `onBackpressureDrop` methods (the one with and the one without an action) have the same name, but in RxScala, you introduce the ugly name `onBackpressureDropWithDropAction`. I guess that's because otherwise the implicit conversion to `ExperimentalAPI` doesn't kick in? Or would it not even work if it was directly in `Observable`?

**Comment by zsxwing** [comment]
It's because `overload` and `implicit conversion` cannot work together. Better name? Or we should consider another approach to add experimental APIs?

**Comment by zsxwing** [comment]
@samuelgruetter how about I just update RxJava? I would like to release a new version to test the build scripts.

**Comment by samuelgruetter** [comment]
As you wish ;-) Or I'd also be fine with renaming `onBackpressureDropWithDropAction` into something better (but what...?)

**Comment by zsxwing** [comment]
onBackpressureDropWith or onBackpressureDropWithAction?

**Comment by jbripley** [comment]
onBackpressureDropDo would be somewhat analogues with the doOn*(Action) methods?

**Comment by zsxwing** [comment]
> onBackpressureDropDo would be somewhat analogues with the doOn*(Action) methods?

I think onBackpressureDropDo is better. @samuelgruetter thoughts?

**Comment by samuelgruetter** [comment]
+1 for onBackpressureDropDo

**Comment by zsxwing** [comment]
Updated the method name.

**Comment by samuelgruetter** [comment]
LGTM

**Pull request merged**
