### PR TITLE
0.26.2 Release Note

### PR DESCRIPTION
**Pull request by zsxwing**

### CODE REVIEW

**Comment by zsxwing** [comment]
Blocked by #197

**Comment by samuelgruetter** [comment]
LGTM except https://github.com/zsxwing/RxScala/pull/5

**Comment by zsxwing** [comment]
I will create a new release once  #197 is merged.

**Comment by zsxwing** [comment]
0.26.2 is out: http://search.maven.org/#search%7Cga%7C1%7C%22rxscala%22%20AND%20g%3A%22io.reactivex%22 🎉

**Pull request merged**
