### PR TITLE
Add an implicit toSerialized method

### PR DESCRIPTION
**Pull request by zsxwing**
An convenient implicit method for `SerializedSubject`.

### CODE REVIEW

**Comment by samuelgruetter** [comment]
Let's do the same as Java does, but that's not yet decided I guess: https://github.com/ReactiveX/RxJava/issues/1748

And btw why not an instance method instead of an extension method? The default implementation in `Subject` would be to return a new `SerializedSubject`, and `SerializedSubject` would override it and just return `this`. This would be more extensible, because users could add a `MyOwnSerializeSubject`, which does not extend `SerializedSubject`, but only `Subject`, and also returns `this` in the `toSerialized` method.

**Comment by zsxwing** [comment]
IMO, an instance `toSerialized` method also cannot support a custom `MyOwnSerializeSubject` because it can not change the behaviors of other `Subject`s. That's why I prefer an extension method.

**Comment by samuelgruetter** [comment]
I'm sorry, I don't get what you mean here ;-) Could you please explain?

**Comment by zsxwing** [comment]
Never mind. I misunderstood your comment. Now I agree with you.

**Pull request closed without merging**
