### PR TITLE
RxScala 0.25.0 Release Note

### PR DESCRIPTION
**Pull request by zsxwing**
This is the release note for 0.25.0. I would like to release 0.25.0 after #170 is merged.

Is there any other issue should be resolved for 0.25.0?

### CODE REVIEW

**Comment by zsxwing** [comment]
cc @samuelgruetter @headinthebox

**Comment by samuelgruetter** [comment]
LGTM

**Comment by headinthebox** [comment]
Thanks @zsxwing!

**Comment by zsxwing** [comment]
0.25.0 has been pushed to Maven Central :)

**Pull request merged**
