### PR TITLE
Update Scala version to 2.12.0 final

### PR DESCRIPTION
**Pull request by ruippeixotog**
Updates Scala to 2.12.0 final and makes this the default Scala version from now on.

### CODE REVIEW

**Review by samuelgruetter — APPROVED** [review]
LGTM

**Comment by zsxwing** [comment]
👍 Thanks!

**Comment by ruippeixotog** [comment]
No problem at all! Please publish a Scala 2.12 version of RxScala as soon as you can :)

**Comment by OlegIlyenko** [comment]
👍

**Comment by zsxwing** [comment]
@ruippeixotog  RxScala 0.26.4 should be available in maven central in several hours. Then you can try the Scala 2.12 version :)

**Pull request merged**
