### PR TITLE
Merge Rxjava #1701

### PR DESCRIPTION
**Pull request by zsxwing**
Including:
- Merge https://github.com/ReactiveX/RxJava/pull/1701
- Upgrade to RxJava 1.0.0-rc.4
- Remove 'parallel' operator

### CODE REVIEW

**Comment by zsxwing** [comment]
The build error is `unresolved dependency: me.lessis#bintray-sbt;0.1.2: not found`

I checked other successful builds and found they downloaded it from https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/me.lessis/bintray-sbt/scala_2.10/sbt_0.13/0.1.2/jars/bintray-sbt.jar

But now this link cannot be accessed. Does anyone know why it's removed from `repo.scala-sbt.org`?

**Comment by zsxwing** [comment]
Should I add 

``` Scala
resolvers += Resolver.url(
  "bintray-sbt-plugin-releases",
    url("http://dl.bintray.com/content/sbt/sbt-plugin-releases"))(
        Resolver.ivyStylePatterns)
```

into `project/bintray.sbt`? @jmhofer

**Comment by jmhofer** [comment]
Probably. No idea though why it doesn't work anymore  without this.

**Comment by zsxwing** [comment]
> Probably. No idea though why it doesn't work anymore without this.

Because `me.lessis#bintray-sbt;0.1.2` is removed from `repo.scala-sbt.org`. I can only find `0.1.0` in https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/me.lessis/bintray-sbt/scala_2.10/sbt_0.13/ now.

**Pull request merged**
