### PR TITLE
Upgrade to RxJava 1.0.0-RC5

### PR DESCRIPTION
**Pull request by jbripley**
- If RxJava is updated with the same signature changes with ReactiveX/RxJava#1720, the conversion from RxScala to RxJava can be simplified, without any external signature changes in RxScala.

### CODE REVIEW

**Comment by samuelgruetter** [comment]
Nice, but let's wait with this until there's an RxJava release which contains https://github.com/ReactiveX/RxJava/pull/1720.

**Comment by benjchristensen** [comment]
Are you ready to proceed with this now that 1.0.0-RC5 of RxJava is released with these changes?

**Comment by jbripley** [comment]
Yes, I'll push an update to this PR later today or tomorrow.

**Comment by jbripley** [comment]
Should I include the removal of groupByUntil in this PR as well, since I need to update to RxJava 1.0.0-RC5?

**Comment by benjchristensen** [comment]
Good point ... yes. But the name of the pull request should be changed then so it's clear for historical purposes that it was upgrading to 1.0.0-RC5 and all related changes.

**Comment by samuelgruetter** [comment]
LGTM

**Comment by headinthebox** [comment]
Ship it.

**Pull request merged**
