### PR TITLE
Fix directory structure of examples sub-project

### PR DESCRIPTION
**Pull request by samuelgruetter**
With the current structure of the `examples` directory, the `compile` and `test` sbt commands succeed, but they do nothing, and the `run` command doesn't detect the main classes:

```
> projects
[info] In file:/home/sam/Documents/git/ReactiveX/RxScala/
[info]     examples
[info]   * root
> project examples
[info] Set current project to examples (in build file:/home/sam/Documents/git/ReactiveX/RxScala/)
> test
[warn] Credentials file /home/sam/.bintray/.credentials does not exist
[info] Updating {file:/home/sam/Documents/git/ReactiveX/RxScala/}examples...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 2 s, completed Sep 27, 2014 2:56:52 AM
> compile
[warn] Credentials file /home/sam/.bintray/.credentials does not exist
[success] Total time: 0 s, completed Sep 27, 2014 2:56:59 AM
> project
[info] examples (in build file:/home/sam/Documents/git/ReactiveX/RxScala/)
> run
[warn] Credentials file /home/sam/.bintray/.credentials does not exist
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last examples/compile:run for the full output.
[error] (examples/compile:run) No main class detected.
[error] Total time: 0 s, completed Sep 27, 2014 2:57:10 AM
```

This PR changes the directory structure of the `examples` project to the sbt default structure. Now the files are not ignored any more, but the examples project does not inherit the library dependencies of the root project, so the compilation fails:

```
> projects
[info] In file:/home/sam/Documents/git/ReactiveX/RxScala/
[info]     examples
[info]   * root
> project examples
[info] Set current project to examples (in build file:/home/sam/Documents/git/ReactiveX/RxScala/)
> test
[warn] Credentials file /home/sam/.bintray/.credentials does not exist
[info] Compiling 7 Scala sources to /home/sam/Documents/git/ReactiveX/RxScala/examples/target/scala-2.10/classes...
[info] Compiling 4 Scala sources and 1 Java source to /home/sam/Documents/git/ReactiveX/RxScala/examples/target/scala-2.10/test-classes...
[error] /home/sam/Documents/git/ReactiveX/RxScala/examples/src/test/scala/rx/lang/scala/examples/RxScalaDemo.scala:30: object junit is not a member of package org
[error] import org.junit.Assert.assertEquals
...
```

I tried to solve this following this [guide](http://www.scala-sbt.org/0.13.5/docs/Getting-Started/Multi-Project.html), but didn't succeed.

@jmhofer any idea how to make this work?

### CODE REVIEW

**Comment by samuelgruetter** [comment]
Travis says the build passed, but it just says so because it only built the root project, but not the examples project. This should be fixed as well.

**Comment by jmhofer** [comment]
The subproject probably just doesn't inherit any test dependencies. We'll have to use "dependsOn (root % "test->test") or something similar.

**Comment by jmhofer** [comment]
Thanks for fixing this!

I took the liberty of modifying the `dependsOn` line in the build, and together with removing the deprecations from the examples, it compiles, tests and runs again now.

**Comment by samuelgruetter** [comment]
Cool, thanks! Now I'm very happy with the build infrastructure :-)

**Pull request merged**
