### PR TITLE
Add a type parameter for 'empty' and 'never'

### PR DESCRIPTION
**Pull request by zsxwing**
As per #80. 

~~Adding type parameters breaks the source compatibility. Hold off until we prepare to release 0.24.0.~~

### CODE REVIEW

**Comment by samuelgruetter** [comment]
> Adding type parameters breaks the source compatibility.

Why? Can you give an example which works before this PR but not after?

**Comment by zsxwing** [comment]
> Why? Can you give an example which works before this PR but not after?

Never mind. I was wrong...

**Comment by headinthebox** [comment]
No ... it should be `Nothing`!

**Comment by headinthebox** [comment]
I'm going to close this; let's not make our lives worse as a response to making our lives easier.

**Pull request closed without merging**
